import { ORDER_STATUSES } from "./statuses"

export const SIMPLE_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [
    ORDER_STATUSES.PREPARING,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.PREPARING]: [
    ORDER_STATUSES.SERVED,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.SERVED]: [],

  [ORDER_STATUSES.CANCELLED]: [],
} as const

export const ADVANCED_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [
    ORDER_STATUSES.PREPARING,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.PREPARING]: [
    ORDER_STATUSES.READY,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.READY]: [
    ORDER_STATUSES.SERVED,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.SERVED]: [],

  [ORDER_STATUSES.CANCELLED]: [],
} as const