"use client";

export default function StaffTableHeader() {
  return (
    <thead
      className="
        sticky
        top-0
        z-30
      "
    >
      <tr
        className="
          border-b
          border-[var(--color-border)]
          bg-[var(--color-surface)]
          backdrop-blur-xl
          shadow-sm
        "
      >
        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-6
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Employee
        </th>

        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-4
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Employee ID
        </th>

        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-4
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Role
        </th>

        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-4
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Shift
        </th>

        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-4
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Status
        </th>

        <th
          className="
            sticky
            top-0
            bg-[var(--color-surface)]
            px-4
            py-4
            text-left
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Joined
        </th>

        <th
          className="
            sticky
            top-0
            w-[72px]
            bg-[var(--color-surface)]
            px-4
            py-4
            text-right
            text-xs
            font-bold
            uppercase
            tracking-[0.12em]
            text-[var(--color-text-muted)]
          "
        >
          Actions
        </th>
      </tr>
    </thead>
  );
}